const R = {
  login: "/api/login",
  bootstrap: "/api/bootstrap",
  bootstrapAppTitle: "/api/bootstrap/app-title",
  bootstrapAppIcon: "/api/bootstrap/app-icon",
  bootstrapTimezone: "/api/bootstrap/timezone",
  bootstrapSeedOwner: "/api/bootstrap/seed-owner",
  setupFinish: "/api/setup/finish",
  users: "/api/users",
  documentsTree: "/api/documents/tree",
  document: (slug) => `/api/document/${slug}`,
  documentMove: "/api/document/move",
  documentRestore: (slug) => `/api/documentrestore/${slug}`,
  documentBacklinks: (slug) => `/api/document/backlinks/${slug}`,
  documentHistory: (slug) => `/api/documenthistory/${slug}`,
  documentHistoryDiff: (slug, id) =>
    `/api/documenthistory/diff/${slug}?id=${id}`,
  documentsSearch: (q) => `/api/documents/search?${q}`,
  startPage: "/api/start-page",
  uploadImage: "/api/upload-image",
  backups: "/api/backups",
  backup: "/api/backup",
  backupFile: "/api/backup/file",
  backupsUpload: "/api/backups/upload",
  backupRestore: "/api/backup/restore",
  logout: "/api/logout",
  me: "/api/me",
  register: "/api/register",
  nuke: "/api/nuke",
  userPrefs: "/api/user/preferences",
  uploadImageXHR: "/api/upload-image",
};

export default R;
